# air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./main.go"
  bin = "./tmp/main"
  include_ext = ["go", "yml", "yaml", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "frontend/node_modules"]
  exclude_ext = []
  exclude_regex = []
  follow_symlink = false
  env = ["CGO_ENABLED=1"]
  log = "info"

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[misc]
  clean_on_exit = true
